In [ ]:
!sudo apt update
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
#Check this site for the latest download link https://www.apache.org/dyn/closer.lua/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
!wget -q https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
!tar xf spark-3.2.1-bin-hadoop3.2.tgz
!pip install -q findspark
!pip install pyspark
!pip install py4j

import os
import sys
# os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
# os.environ["SPARK_HOME"] = "/content/spark-3.2.1-bin-hadoop3.2"


import findspark
findspark.init()
findspark.find()

import pyspark

from pyspark.sql import DataFrame, SparkSession
from typing import List
import pyspark.sql.types as T
import pyspark.sql.functions as F

spark= SparkSession \
       .builder \
       .appName("Our First Spark Example") \
       .getOrCreate()

spark

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Ign:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy Release [5,713 B]
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:9 https://r2u.stat.illinois.edu/ubuntu jammy Release.gpg [793 B]
Get:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:13 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [910 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2,396 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [8,218 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,118 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,552 kB]
Get:18 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [27.8 kB]
Fetched 16.5 MB in 4s (3,777 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
50 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
tar: spark-3.2.1-bin-hadoop3.2.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Collecting pyspark
  Downloading pyspark-3.5.1.tar.gz (317.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 MB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488490 sha256=57f0290c60f77b5346ca06c00b87c501d8357c8c6f93a5b91bfe50130b8d7a06
  Stored in directory: /root/.cache/pip/wheels/80/1d/60/2c256ed38dddce2fdd93be545214a63e02fbd8d74fb0b7f3a6
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.1
Requirement already satisfied: py4j in /usr/local/lib/python3.10/dist-packages (0.10.9.7)

In [ ]:
import pandas as pd

In [ ]:
customer = pd.read_excel('Customer.xls')

In [ ]:
customer

     Customer_ID     First     Last  Age Country
0              1    Joseph     Rice   43     USA
1              2      Gary    Moore   71     USA
2              3      John   Walker   44      UK
3              4      Eric   Carter   38      UK
4              5   William  Jackson   58     UAE
..           ...       ...      ...  ...     ...
245          246    Justin  Stewart   73     USA
246          247      John   Miller   53     USA
247          248    Thomas  Hickman   23      UK
248          249  Patricia   Garcia   19      UK
249          250   Stephen    Jones   22     USA

[250 rows x 5 columns]

In [ ]:
customer_df = spark.createDataFrame(customer)

In [ ]:
customer_df.show()

+-----------+----------+----------+---+-------+
|Customer_ID|     First|      Last|Age|Country|
+-----------+----------+----------+---+-------+
|          1|    Joseph|      Rice| 43|    USA|
|          2|      Gary|     Moore| 71|    USA|
|          3|      John|    Walker| 44|     UK|
|          4|      Eric|    Carter| 38|     UK|
|          5|   William|   Jackson| 58|    UAE|
|          6|    N!cole|     Jones| 33|    USA|
|          7|     David|     Davis| 59|    USA|
|          8|     Jason|Montgomery| 58|     UK|
|          9|      Kent|    Weaver| 61|     UK|
|         10|   Darrell|    Dillon| 50|    UAE|
|         11|Jacqueline|      Wang| 22|    USA|
|         12|      Jodi|  Gonzalez| 69|    USA|
|         13|      Omar|    Martin| 28|     UK|
|         14|    N!cole|      Lara| 77|     UK|
|         15|     Jason|     Brown| 63|    UAE|
|         16|     David|    Benson| 61|    USA|
|         17|  Kimberly|      Mora| 34|    USA|
|         18|      Erik|    Macias| 25|     UK|
|         19|     James|   Johnson| 67|     UK|
|         20|     Derek|  Peterson| 36|    UAE|
+-----------+----------+----------+---+-------+
only showing top 20 rows

In [ ]:
customer_df.describe().show()

+-------+-----------------+-------+------+-----------------+-------+
|summary|      Customer_ID|  First|  Last|              Age|Country|
+-------+-----------------+-------+------+-----------------+-------+
|  count|              250|    250|   250|              250|    250|
|   mean|            125.5|   NULL|  NULL|           47.576|   NULL|
| stddev|72.31297716638879|   NULL|  NULL|18.97801052624159|   NULL|
|    min|                1|  Aaron| Adams|               18|    UAE|
|    max|              250|Zachary|Zamora|               80|    USA|
+-------+-----------------+-------+------+-----------------+-------+

In [ ]:
customer_df.filter(customer_df.Customer_ID.isNull()).show()

+-----------+-----+----+---+-------+
|Customer_ID|First|Last|Age|Country|
+-----------+-----+----+---+-------+
+-----------+-----+----+---+-------+

In [ ]:
customer_df.filter(customer_df.Country.isNull()).show()

+-----------+-----+----+---+-------+
|Customer_ID|First|Last|Age|Country|
+-----------+-----+----+---+-------+
+-----------+-----+----+---+-------+

In [ ]:
customer_df.filter(customer_df.First.isNull()).show()

+-----------+-----+----+---+-------+
|Customer_ID|First|Last|Age|Country|
+-----------+-----+----+---+-------+
+-----------+-----+----+---+-------+

In [ ]:
customer_df.filter(customer_df.Last.isNull()).show()

+-----------+-----+----+---+-------+
|Customer_ID|First|Last|Age|Country|
+-----------+-----+----+---+-------+
+-----------+-----+----+---+-------+

In [ ]:
customer_df \
    .groupby('Customer_ID') \
    .count() \
    .sort('count',ascending=False)\
    .show(300)

+-----------+-----+
|Customer_ID|count|
+-----------+-----+
|         26|    1|
|         29|    1|
|         65|    1|
|         19|    1|
|         54|    1|
|        112|    1|
|        113|    1|
|         22|    1|
|          7|    1|
|         77|    1|
|         34|    1|
|         50|    1|
|         94|    1|
|        110|    1|
|         57|    1|
|         32|    1|
|         43|    1|
|         84|    1|
|         31|    1|
|        119|    1|
|         39|    1|
|         98|    1|
|        116|    1|
|         25|    1|
|        124|    1|
|         95|    1|
|         71|    1|
|          6|    1|
|         68|    1|
|         72|    1|
|         87|    1|
|         58|    1|
|        107|    1|
|          9|    1|
|         27|    1|
|         63|    1|
|         51|    1|
|         56|    1|
|         52|    1|
|         17|    1|
|         79|    1|
|        103|    1|
|         41|    1|
|         28|    1|
|         33|    1|
|         88|    1|
|        114|    1|
|          5|    1|
|          1|    1|
|        115|    1|
|         96|    1|
|        104|    1|
|         10|    1|
|        120|    1|
|         89|    1|
|         85|    1|
|        106|    1|
|        111|    1|
|         48|    1|
|         67|    1|
|        100|    1|
|        105|    1|
|        108|    1|
|         44|    1|
|        123|    1|
|         61|    1|
|          3|    1|
|         37|    1|
|        101|    1|
|         83|    1|
|         12|    1|
|         55|    1|
|         74|    1|
|          8|    1|
|         62|    1|
|         11|    1|
|         49|    1|
|         35|    1|
|         80|    1|
|          2|    1|
|         66|    1|
|         76|    1|
|        102|    1|
|          4|    1|
|         92|    1|
|        118|    1|
|         13|    1|
|         36|    1|
|         75|    1|
|         78|    1|
|         18|    1|
|        125|    1|
|         69|    1|
|         14|    1|
|         21|    1|
|         59|    1|
|        122|    1|
|         15|    1|
|         81|    1|
|         38|    1|
|         82|    1|
|         97|    1|
|         30|    1|
|         42|    1|
|         73|    1|
|         90|    1|
|         23|    1|
|        117|    1|
|        121|    1|
|         46|    1|
|         20|    1|
|         70|    1|
|         99|    1|
|         86|    1|
|        109|    1|
|         60|    1|
|         93|    1|
|         40|    1|
|         16|    1|
|         64|    1|
|         91|    1|
|         45|    1|
|         47|    1|
|         53|    1|
|         24|    1|
|        191|    1|
|        222|    1|
|        243|    1|
|        155|    1|
|        167|    1|
|        237|    1|
|        241|    1|
|        198|    1|
|        130|    1|
|        196|    1|
|        184|    1|
|        188|    1|
|        126|    1|
|        202|    1|
|        228|    1|
|        149|    1|
|        229|    1|
|        190|    1|
|        136|    1|
|        144|    1|
|        212|    1|
|        187|    1|
|        201|    1|
|        232|    1|
|        203|    1|
|        145|    1|
|        157|    1|
|        181|    1|
|        227|    1|
|        143|    1|
|        161|    1|
|        193|    1|
|        215|    1|
|        221|    1|
|        158|    1|
|        178|    1|
|        234|    1|
|        239|    1|
|        150|    1|
|        146|    1|
|        174|    1|
|        170|    1|
|        209|    1|
|        236|    1|
|        139|    1|
|        246|    1|
|        226|    1|
|        242|    1|
|        208|    1|
|        248|    1|
|        138|    1|
|        207|    1|
|        235|    1|
|        153|    1|
|        250|    1|
|        185|    1|
|        219|    1|
|        214|    1|
|        128|    1|
|        197|    1|
|        177|    1|
|        179|    1|
|        224|    1|
|        142|    1|
|        168|    1|
|        247|    1|
|        131|    1|
|        218|    1|
|        132|    1|
|        127|    1|
|        210|    1|
|        205|    1|
|        225|    1|
|        220|    1|
|        249|    1|
|        192|    1|
|        213|    1|
|        156|    1|
|        160|    1|
|        206|    1|
|        200|    1|
|        141|    1|
|        182|    1|
|        186|    1|
|        171|    1|
|        166|    1|
|        199|    1|
|        154|    1|
|        162|    1|
|        244|    1|
|        164|    1|
|        176|    1|
|        134|    1|
|        245|    1|
|        175|    1|
|        233|    1|
|        163|    1|
|        230|    1|
|        172|    1|
|        140|    1|
|        216|    1|
|        137|    1|
|        173|    1|
|        194|    1|
|        135|    1|
|        238|    1|
|        129|    1|
|        165|    1|
|        223|    1|
|        180|    1|
|        195|    1|
|        133|    1|
|        151|    1|
|        159|    1|
|        217|    1|
|        231|    1|
|        189|    1|
|        204|    1|
|        147|    1|
|        183|    1|
|        240|    1|
|        152|    1|
|        148|    1|
|        169|    1|
|        211|    1|
+-----------+-----+

In [ ]:
order = spark.read.csv('Order.csv', header=True, inferSchema=True)

In [ ]:
order.show()

+--------+--------+------+-----------+
|Order_ID|    Item|Amount|Customer_ID|
+--------+--------+------+-----------+
|       1|Keyboard|   400|        139|
|       2|   Mouse|   300|        250|
|       3| Monitor| 12000|        239|
|       4|Keyboard|   400|        153|
|       5|Mousepad|   250|        153|
|       6|Harddisk|  5000|        164|
|       7|  Webcam|   350|        124|
|       8|Mousepad|   200|         98|
|       9| DDR RAM|  1500|        119|
|      10| Headset|   900|        159|
|      11|Keyboard|   400|        167|
|      12|   Mouse|   300|        157|
|      13| Monitor| 12000|         49|
|      14|Keyboard|   400|        234|
|      15|Mousepad|   250|        202|
|      16|Harddisk|  5000|        181|
|      17|  Webcam|   350|         15|
|      18|Mousepad|   200|        177|
|      19| DDR RAM|  1500|          5|
|      20| Headset|   900|        225|
+--------+--------+------+-----------+
only showing top 20 rows

In [ ]:
order.describe().show()

+-------+-----------------+-------+-----------------+----------------+
|summary|         Order_ID|   Item|           Amount|     Customer_ID|
+-------+-----------------+-------+-----------------+----------------+
|  count|              250|    250|              250|             250|
|   mean|            125.5|   NULL|           2130.0|         130.404|
| stddev|72.31297716638879|   NULL|3575.434930153119|69.1927113881003|
|    min|                1|DDR RAM|              200|               4|
|    max|              250| Webcam|            12000|             250|
+-------+-----------------+-------+-----------------+----------------+

In [ ]:
order \
    .groupby('Order_ID') \
    .count() \
    .sort('count',ascending=False)\
    .show(300)

+--------+-----+
|Order_ID|count|
+--------+-----+
|     148|    1|
|     243|    1|
|      31|    1|
|      85|    1|
|     137|    1|
|      65|    1|
|      53|    1|
|     133|    1|
|      78|    1|
|     108|    1|
|     155|    1|
|      34|    1|
|     193|    1|
|     211|    1|
|     101|    1|
|     115|    1|
|     126|    1|
|      81|    1|
|      28|    1|
|     183|    1|
|     210|    1|
|      76|    1|
|      26|    1|
|      27|    1|
|      44|    1|
|     159|    1|
|     192|    1|
|     103|    1|
|     236|    1|
|      12|    1|
|     223|    1|
|      91|    1|
|     222|    1|
|      22|    1|
|     128|    1|
|     209|    1|
|     122|    1|
|     230|    1|
|      93|    1|
|     157|    1|
|     190|    1|
|     225|    1|
|     232|    1|
|     233|    1|
|     246|    1|
|     111|    1|
|     224|    1|
|      47|    1|
|     140|    1|
|     177|    1|
|     132|    1|
|     152|    1|
|     185|    1|
|     146|    1|
|       1|    1|
|     206|    1|
|      52|    1|
|     212|    1|
|     182|    1|
|      13|    1|
|     218|    1|
|       6|    1|
|      16|    1|
|      86|    1|
|     168|    1|
|     205|    1|
|       3|    1|
|     142|    1|
|     178|    1|
|      20|    1|
|      40|    1|
|     164|    1|
|     169|    1|
|     139|    1|
|      94|    1|
|     250|    1|
|      57|    1|
|      54|    1|
|     120|    1|
|      96|    1|
|     235|    1|
|      48|    1|
|       5|    1|
|     163|    1|
|     191|    1|
|      19|    1|
|      92|    1|
|      64|    1|
|     117|    1|
|     227|    1|
|      41|    1|
|     154|    1|
|      15|    1|
|      43|    1|
|     112|    1|
|     165|    1|
|     179|    1|
|     189|    1|
|     207|    1|
|      37|    1|
|      61|    1|
|     127|    1|
|      88|    1|
|     197|    1|
|     107|    1|
|     202|    1|
|       9|    1|
|      17|    1|
|     231|    1|
|      72|    1|
|     175|    1|
|      35|    1|
|     196|    1|
|     217|    1|
|     229|    1|
|     114|    1|
|     173|    1|
|     220|    1|
|       4|    1|
|      55|    1|
|      59|    1|
|       8|    1|
|     100|    1|
|     241|    1|
|     161|    1|
|      23|    1|
|      39|    1|
|      49|    1|
|     176|    1|
|       7|    1|
|     162|    1|
|     130|    1|
|     238|    1|
|     244|    1|
|      84|    1|
|     136|    1|
|     247|    1|
|      87|    1|
|     171|    1|
|      51|    1|
|     194|    1|
|      69|    1|
|     129|    1|
|     166|    1|
|      97|    1|
|     234|    1|
|     239|    1|
|      63|    1|
|      10|    1|
|      77|    1|
|     102|    1|
|      50|    1|
|      45|    1|
|     216|    1|
|      38|    1|
|      82|    1|
|     181|    1|
|     249|    1|
|     167|    1|
|      80|    1|
|     240|    1|
|      25|    1|
|      73|    1|
|     245|    1|
|     113|    1|
|     237|    1|
|      24|    1|
|     160|    1|
|      70|    1|
|      62|    1|
|     121|    1|
|     125|    1|
|     156|    1|
|     143|    1|
|     219|    1|
|      95|    1|
|      29|    1|
|     226|    1|
|      21|    1|
|     214|    1|
|      98|    1|
|     195|    1|
|      32|    1|
|      60|    1|
|      90|    1|
|      75|    1|
|     203|    1|
|     221|    1|
|     141|    1|
|     151|    1|
|     145|    1|
|     200|    1|
|      56|    1|
|     109|    1|
|     213|    1|
|     228|    1|
|     170|    1|
|     105|    1|
|      58|    1|
|     188|    1|
|      11|    1|
|      33|    1|
|     204|    1|
|      83|    1|
|     110|    1|
|     150|    1|
|      68|    1|
|      71|    1|
|     106|    1|
|     116|    1|
|     147|    1|
|      14|    1|
|     198|    1|
|     123|    1|
|     158|    1|
|     199|    1|
|     242|    1|
|     135|    1|
|     248|    1|
|      42|    1|
|     119|    1|
|       2|    1|
|      79|    1|
|     201|    1|
|     131|    1|
|     149|    1|
|     118|    1|
|     124|    1|
|      30|    1|
|      99|    1|
|     184|    1|
|      66|    1|
|      46|    1|
|      67|    1|
|     186|    1|
|     174|    1|
|     215|    1|
|     172|    1|
|     144|    1|
|     153|    1|
|      18|    1|
|      74|    1|
|     138|    1|
|     104|    1|
|     180|    1|
|     134|    1|
|      36|    1|
|     187|    1|
|     208|    1|
|      89|    1|
+--------+-----+

In [ ]:
order \
    .groupby(['Order_ID','Customer_ID']) \
    .count() \
    .sort('count',ascending=False)\
    .show(300)

+--------+-----------+-----+
|Order_ID|Customer_ID|count|
+--------+-----------+-----+
|     148|        229|    1|
|     156|         71|    1|
|     168|        193|    1|
|     141|         59|    1|
|     154|        114|    1|
|     157|        101|    1|
|      49|        194|    1|
|      84|         39|    1|
|      94|         80|    1|
|     180|         86|    1|
|     241|        224|    1|
|     183|         55|    1|
|      70|         50|    1|
|     224|        221|    1|
|     132|        183|    1|
|     222|        238|    1|
|      88|         91|    1|
|     155|        247|    1|
|       8|         98|    1|
|      48|        222|    1|
|     100|        231|    1|
|     230|        111|    1|
|      28|        188|    1|
|      79|        249|    1|
|     162|        134|    1|
|     176|        159|    1|
|     113|        167|    1|
|     147|        232|    1|
|     188|        249|    1|
|     167|        143|    1|
|      86|        124|    1|
|     247|        135|    1|
|      14|        234|    1|
|     189|        195|    1|
|     229|         57|    1|
|      87|        108|    1|
|     211|        239|    1|
|      37|         92|    1|
|     191|         70|    1|
|     193|         92|    1|
|     243|        123|    1|
|      68|        144|    1|
|     171|         55|    1|
|      35|        209|    1|
|      76|         38|    1|
|     129|        107|    1|
|     119|        184|    1|
|     164|         85|    1|
|      33|        158|    1|
|     204|         28|    1|
|     213|        118|    1|
|     233|        206|    1|
|     198|         57|    1|
|     232|        190|    1|
|      27|         60|    1|
|      71|         70|    1|
|     239|        223|    1|
|       2|        250|    1|
|      77|         87|    1|
|     215|        176|    1|
|     179|         67|    1|
|     195|         24|    1|
|      98|        195|    1|
|      58|         64|    1|
|     197|        166|    1|
|       7|        124|    1|
|      20|        225|    1|
|     236|        102|    1|
|      90|        161|    1|
|      85|        193|    1|
|     103|        242|    1|
|      32|        174|    1|
|     250|        223|    1|
|     115|        186|    1|
|     200|        178|    1|
|      57|        101|    1|
|     146|        247|    1|
|     216|         85|    1|
|      63|        221|    1|
|     184|        146|    1|
|      99|         86|    1|
|     117|          8|    1|
|      38|        105|    1|
|      16|        181|    1|
|      23|         68|    1|
|      55|        125|    1|
|     121|         35|    1|
|     140|        138|    1|
|      24|         86|    1|
|     170|        214|    1|
|     172|        122|    1|
|     206|         57|    1|
|     142|         84|    1|
|     181|         23|    1|
|      78|        211|    1|
|     159|        172|    1|
|      12|        157|    1|
|      44|        126|    1|
|     130|         13|    1|
|      36|         52|    1|
|      21|        171|    1|
|      41|        200|    1|
|     150|         89|    1|
|     143|        143|    1|
|     169|        236|    1|
|     245|         50|    1|
|     219|         97|    1|
|     161|         89|    1|
|     205|        208|    1|
|     111|        243|    1|
|      29|         33|    1|
|      74|        112|    1|
|     166|         12|    1|
|     101|        226|    1|
|     136|        123|    1|
|     152|         47|    1|
|      13|         49|    1|
|     104|         53|    1|
|      72|         89|    1|
|     212|        103|    1|
|     160|        246|    1|
|     208|         29|    1|
|      53|        193|    1|
|     190|        197|    1|
|     238|        200|    1|
|     202|         98|    1|
|      50|        150|    1|
|      89|        193|    1|
|     226|         65|    1|
|      52|        192|    1|
|     163|        166|    1|
|     173|         13|    1|
|       1|        139|    1|
|      80|        238|    1|
|     218|        151|    1|
|     175|        203|    1|
|     220|        223|    1|
|      47|         78|    1|
|     138|         63|    1|
|     207|        235|    1|
|     192|        218|    1|
|     151|        208|    1|
|     114|         69|    1|
|      59|        164|    1|
|      65|        198|    1|
|     118|          4|    1|
|      56|        228|    1|
|     145|         53|    1|
|     165|        221|    1|
|      60|        244|    1|
|     214|         92|    1|
|      39|         99|    1|
|      83|        129|    1|
|     108|        152|    1|
|     186|        166|    1|
|     128|        191|    1|
|     110|         32|    1|
|     185|         66|    1|
|     234|         13|    1|
|     177|         63|    1|
|      26|         56|    1|
|      30|        157|    1|
|      69|        136|    1|
|     106|        119|    1|
|       9|        119|    1|
|     194|        235|    1|
|     135|         95|    1|
|     112|        143|    1|
|     144|         10|    1|
|     153|         23|    1|
|     221|        198|    1|
|      81|        247|    1|
|     158|          8|    1|
|     187|        117|    1|
|     242|         63|    1|
|     244|        215|    1|
|       6|        164|    1|
|      31|         87|    1|
|     109|          8|    1|
|     235|         37|    1|
|       4|        153|    1|
|     217|         78|    1|
|     223|         96|    1|
|      66|         30|    1|
|     105|        107|    1|
|      46|         81|    1|
|      61|        118|    1|
|     149|         20|    1|
|     137|        103|    1|
|     225|        113|    1|
|     228|        153|    1|
|     133|         98|    1|
|     237|        157|    1|
|      67|        201|    1|
|      92|        145|    1|
|      82|        156|    1|
|      93|        229|    1|
|     248|        110|    1|
|     246|        186|    1|
|      75|         70|    1|
|     210|        106|    1|
|     240|        101|    1|
|     107|         17|    1|
|     126|         47|    1|
|     131|         70|    1|
|       3|        239|    1|
|      34|        134|    1|
|      62|         96|    1|
|      96|        129|    1|
|     249|        176|    1|
|     196|        196|    1|
|      95|        172|    1|
|      43|         61|    1|
|      15|        202|    1|
|      17|         15|    1|
|      19|          5|    1|
|      64|        190|    1|
|     122|         73|    1|
|     227|        134|    1|
|     120|         96|    1|
|     201|        109|    1|
|     124|        151|    1|
|     199|        229|    1|
|     174|        181|    1|
|      42|        180|    1|
|      73|        151|    1|
|     134|         23|    1|
|     203|        207|    1|
|       5|        153|    1|
|     127|         60|    1|
|      22|         67|    1|
|     102|         68|    1|
|      10|        159|    1|
|      40|        249|    1|
|     123|        131|    1|
|     231|        162|    1|
|      51|        146|    1|
|     116|         75|    1|
|     139|         96|    1|
|     209|         40|    1|
|      45|        172|    1|
|      54|         24|    1|
|     125|        249|    1|
|     182|         97|    1|
|      97|        163|    1|
|      11|        167|    1|
|      18|        177|    1|
|      25|          8|    1|
|      91|         99|    1|
|     178|         94|    1|
+--------+-----------+-----+

In [ ]:
ship = spark.read.option("multiline","true").json("Shipping.json")

In [ ]:
ship.show()

+-----------+-----------+---------+
|Customer_ID|Shipping_ID|   Status|
+-----------+-----------+---------+
|        173|          1|  Pending|
|        155|          2|  Pending|
|        242|          3|Delivered|
|        223|          4|  Pending|
|         72|          5|Delivered|
|         29|          6|  Pending|
|        236|          7|  Pending|
|        193|          8|Delivered|
|        199|          9|  Pending|
|         17|         10|Delivered|
|        157|         11|  Pending|
|         37|         12|  Pending|
|        141|         13|Delivered|
|        155|         14|  Pending|
|        131|         15|Delivered|
|         24|         16|  Pending|
|        186|         17|  Pending|
|        177|         18|Delivered|
|        129|         19|  Pending|
|          6|         20|Delivered|
+-----------+-----------+---------+
only showing top 20 rows

In [ ]:
ship.write.csv('ship.csv')

In [ ]:
customer_df.registerTempTable('customer_df')

/usr/local/lib/python3.10/dist-packages/pyspark/sql/dataframe.py:329: FutureWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
  warnings.warn("Deprecated in 2.0, use createOrReplaceTempView instead.", FutureWarning)

In [ ]:
order.registerTempTable('order_df')

In [ ]:
ship.registerTempTable('ship_df')

/usr/local/lib/python3.10/dist-packages/pyspark/sql/dataframe.py:329: FutureWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
  warnings.warn("Deprecated in 2.0, use createOrReplaceTempView instead.", FutureWarning)

In [ ]:
ship.describe().show()

+-------+-----------------+-----------------+---------+
|summary|      Customer_ID|      Shipping_ID|   Status|
+-------+-----------------+-----------------+---------+
|  count|              250|              250|      250|
|   mean|           120.62|            125.5|     NULL|
| stddev|73.89384820952858|72.31297716638879|     NULL|
|    min|                1|                1|Delivered|
|    max|              248|              250|  Pending|
+-------+-----------------+-----------------+---------+

In [ ]:
amt = spark.sql(f'''select c.Country,sum(o.Amount) from customer_df c
join order_df o on c.Customer_ID = o.Customer_ID
group by c.Country
''')

In [ ]:
amt.show()

+-------+-----------+
|Country|sum(Amount)|
+-------+-----------+
|    USA|     238200|
|     UK|     244350|
|    UAE|      49950|
+-------+-----------+

In [ ]:
order_det = spark.sql(f'''select Customer_ID, count(distinct Order_ID) as transactions,
count(Item) as items,
sum(Amount) as total_amt
from order_df
group by Customer_ID
''')

In [ ]:
order_det.show(300)

+-----------+------------+-----+---------+
|Customer_ID|transactions|items|total_amt|
+-----------+------------+-----+---------+
|        243|           1|    1|      400|
|         85|           2|    2|     5400|
|         65|           1|    1|     5000|
|         53|           2|    2|      650|
|         78|           2|    2|      700|
|        108|           1|    1|      350|
|        193|           4|    4|    13950|
|        211|           1|    1|      200|
|        101|           3|    3|     1600|
|        126|           1|    1|      400|
|         81|           1|    1|     5000|
|        183|           1|    1|      300|
|         28|           1|    1|      400|
|        192|           1|    1|      300|
|        159|           2|    2|     5900|
|        103|           2|    2|      650|
|        236|           1|    1|     1500|
|         12|           1|    1|     5000|
|        223|           3|    3|     3300|
|         91|           1|    1|      200|
|        222|           1|    1|      200|
|        209|           1|    1|      250|
|        122|           1|    1|      300|
|        157|           3|    3|     1550|
|        232|           1|    1|      350|
|        190|           2|    2|      700|
|        225|           1|    1|      900|
|        246|           1|    1|      900|
|        224|           1|    1|      400|
|        111|           1|    1|      900|
|         47|           2|    2|     5300|
|        177|           1|    1|      200|
|        152|           1|    1|      200|
|        146|           2|    2|      800|
|        206|           1|    1|    12000|
|         52|           1|    1|     5000|
|         13|           3|    3|    13300|
|        218|           1|    1|      300|
|         86|           3|    3|     2800|
|        178|           1|    1|      900|
|         40|           1|    1|     1500|
|         20|           1|    1|     1500|
|        164|           2|    2|     6500|
|        139|           1|    1|      400|
|        250|           1|    1|      300|
|         94|           1|    1|      200|
|         57|           3|    3|     6700|
|         96|           4|    4|    14700|
|        235|           2|    2|      750|
|        191|           1|    1|      200|
|        163|           1|    1|      350|
|          5|           1|    1|     1500|
|         92|           3|    3|    12750|
|        117|           1|    1|      350|
|         64|           1|    1|      200|
|         15|           1|    1|      350|
|        112|           1|    1|      400|
|        207|           1|    1|    12000|
|         37|           1|    1|      250|
|         61|           1|    1|    12000|
|        197|           1|    1|      900|
|        107|           2|    2|     1750|
|        202|           1|    1|      250|
|        231|           1|    1|      900|
|         17|           1|    1|      350|
|         35|           1|    1|      400|
|        196|           1|    1|     5000|
|        229|           3|    3|    13700|
|        114|           1|    1|      400|
|         55|           2|    2|    12400|
|          4|           1|    1|      200|
|         59|           1|    1|      400|
|          8|           4|    4|     2300|
|        161|           1|    1|      900|
|         23|           3|    3|    12800|
|         39|           1|    1|      400|
|         49|           1|    1|    12000|
|        176|           2|    2|     1750|
|        162|           1|    1|      400|
|        238|           2|    2|     1200|
|        244|           1|    1|      900|
|        136|           1|    1|     1500|
|         84|           1|    1|      300|
|        247|           3|    3|     5650|
|         87|           2|    2|      750|
|        171|           1|    1|      400|
|        194|           1|    1|     1500|
|         69|           1|    1|      400|
|        166|           3|    3|    17350|
|        129|           2|    2|    17000|
|         97|           2|    2|     1800|
|        239|           2|    2|    12400|
|        234|           1|    1|      400|
|         63|           3|    3|      850|
|        102|           1|    1|     5000|
|         10|           1|    1|      400|
|         50|           2|    2|     1150|
|         38|           1|    1|     5000|
|        181|           2|    2|     5400|
|        249|           4|    4|     2850|
|        167|           2|    2|    12400|
|         80|           1|    1|      400|
|         73|           1|    1|      300|
|        113|           1|    1|      250|
|         24|           2|    2|      650|
|         70|           4|    4|     1450|
|        125|           1|    1|      250|
|        156|           1|    1|      300|
|        143|           3|    3|    12650|
|         95|           1|    1|      250|
|         29|           1|    1|      200|
|        226|           1|    1|      400|
|        214|           1|    1|      900|
|        195|           2|    2|     1700|
|         98|           3|    3|    12500|
|         60|           2|    2|      700|
|         32|           1|    1|      900|
|         75|           1|    1|     5000|
|        221|           3|    3|    12650|
|        203|           1|    1|      250|
|        151|           3|    3|    12600|
|        145|           1|    1|      300|
|        200|           2|    2|      600|
|         56|           1|    1|     5000|
|        109|           1|    1|      400|
|        228|           1|    1|     5000|
|        105|           1|    1|      200|
|        188|           1|    1|      200|
|         33|           1|    1|     1500|
|        150|           1|    1|      900|
|        110|           1|    1|      200|
|         71|           1|    1|     5000|
|         68|           2|    2|    12300|
|        106|           1|    1|      900|
|        198|           2|    2|      650|
|        123|           2|    2|    17000|
|        242|           1|    1|    12000|
|        158|           1|    1|    12000|
|        135|           1|    1|      350|
|        119|           2|    2|     6500|
|        201|           1|    1|      350|
|        131|           1|    1|    12000|
|        118|           2|    2|    12400|
|        124|           2|    2|     5350|
|         99|           2|    2|     1900|
|         30|           1|    1|     5000|
|        184|           1|    1|     1500|
|         66|           1|    1|      250|
|        186|           2|    2|     5250|
|         67|           2|    2|     1800|
|        174|           1|    1|      300|
|        215|           1|    1|      400|
|        172|           3|    3|     2000|
|        153|           3|    3|      850|
|        144|           1|    1|      200|
|        138|           1|    1|      900|
|        180|           1|    1|      300|
|        134|           3|    3|     1050|
|        208|           2|    2|      650|
|         89|           3|    3|     1600|
+-----------+------------+-----+---------+

In [ ]:
spark.sql('''select * from order_df where Customer_ID = "78"''').show()

+--------+------+------+-----------+
|Order_ID|  Item|Amount|Customer_ID|
+--------+------+------+-----------+
|      47|Webcam|   350|         78|
|     217|Webcam|   350|         78|
+--------+------+------+-----------+

In [ ]:
product = spark.sql(f'''select Country, Item
from
(select *,
max(count) over (partition by country) as max_count from
(select c.Country,o.Item, count(*) as count from customer_df c
join order_df o on c.Customer_ID = o.Customer_ID
group by 1,2)
)
where count = max_count
''')

In [ ]:
product.show()

+-------+--------+
|Country|    Item|
+-------+--------+
|    UAE|Keyboard|
|     UK|Mousepad|
|    USA|Mousepad|
+-------+--------+

In [ ]:
p1 = spark.sql('''select *,
max(count) over (partition by country) as max_count from
(select c.Country,o.Item, count(*) as count from customer_df c
join order_df o on c.Customer_ID = o.Customer_ID
group by 1,2)
''')

In [ ]:
p1.show(100)

+-------+--------+-----+---------+
|Country|    Item|count|max_count|
+-------+--------+-----+---------+
|    UAE|Keyboard|   12|       12|
|    UAE| Headset|    3|       12|
|    UAE|  Webcam|    5|       12|
|    UAE|Mousepad|    8|       12|
|    UAE| Monitor|    1|       12|
|    UAE|Harddisk|    4|       12|
|    UAE| DDR RAM|    4|       12|
|    UAE|   Mouse|    3|       12|
|     UK| DDR RAM|   11|       24|
|     UK|Harddisk|    8|       24|
|     UK|   Mouse|   13|       24|
|     UK|  Webcam|   10|       24|
|     UK| Headset|   11|       24|
|     UK| Monitor|   13|       24|
|     UK|Keyboard|   23|       24|
|     UK|Mousepad|   24|       24|
|    USA|Harddisk|   13|       18|
|    USA| Headset|   11|       18|
|    USA| DDR RAM|   10|       18|
|    USA|Keyboard|   15|       18|
|    USA|   Mouse|    9|       18|
|    USA| Monitor|   11|       18|
|    USA|  Webcam|   10|       18|
|    USA|Mousepad|   18|       18|
+-------+--------+-----+---------+